[[OpenFHE]]
arch = "aarch64"
git-tree-sha1 = "06d6c18a1e42c4cbdf78268ec288c26d73c75821"
os = "macos"

    [[OpenFHE.download]]
    sha256 = "cac5e5db0c3af2f379574180a4d80ffec567b1dd0de08aae2198da7027ca7e72"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.0+2/OpenFHE.v1.4.0.aarch64-apple-darwin.tar.gz"
[[OpenFHE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32a800529cbc8fd6a78b91ad94489f450b4853ad"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "fada9f41279b98657d19947f9b0e6e12e7db4bf900d8f78d4f19b12666cbb0a0"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.0+2/OpenFHE.v1.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenFHE]]
arch = "aarch64"
git-tree-sha1 = "edaf6b2c0bb65348c66235a28af51818820bd339"
os = "freebsd"

    [[OpenFHE.download]]
    sha256 = "423bab53a9b6aef0447838399428c673ddf5d5322886fc03b63a381ff6de8066"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.0+2/OpenFHE.v1.4.0.aarch64-unknown-freebsd.tar.gz"
[[OpenFHE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d972f5be22326ada0180af246a90585840ccc17"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "352be0df9caebe17790a7f8179e1f14e0bd6829461383c1642724e0b94f74e2c"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.0+2/OpenFHE.v1.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[OpenFHE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e78e441fb382f7ad8aebd4df17c262f11ed9098"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "58c9956c5a70d5f6b3ad86389f2fb59457c63bbcffcb5b5132bcb733ac5c221f"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.0+2/OpenFHE.v1.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenFHE]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7064936b62c0185ec25be6af38b0ea4b89034bcf"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "ecbe794767d9347eb24ec6cc5cc8ae05ab6012ab8bea4458ea54e920d70a16c2"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.0+2/OpenFHE.v1.4.0.riscv64-linux-gnu-cxx11.tar.gz"
[[OpenFHE]]
arch = "x86_64"
git-tree-sha1 = "c9a8119dac4d9f48bd0883822fd8f3047ee7172a"
os = "macos"

    [[OpenFHE.download]]
    sha256 = "43d03fe2e4600fd39dcc4c559e539774d5e2ff9c0928e689c8bb5fdb58a234ff"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.0+2/OpenFHE.v1.4.0.x86_64-apple-darwin.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fecf36244670683e06d0655b5a206ab05e03e16"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "e8446c5df17530d96b9b4daf635a3d1fa1fb6e02d744b184f5cf71aca0e2d1eb"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.0+2/OpenFHE.v1.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenFHE]]
arch = "x86_64"
git-tree-sha1 = "c1e01cb443be2b60fd2e93c0861ce4fa2a0e6b07"
os = "freebsd"

    [[OpenFHE.download]]
    sha256 = "b051a551af7c35ea779c8ee746f10a5b5c430adb2258995d5ab00c07360a70ab"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.0+2/OpenFHE.v1.4.0.x86_64-unknown-freebsd.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a63bebf6a3a41751ae292f0d5a1b80ae40694b8f"
os = "windows"

    [[OpenFHE.download]]
    sha256 = "02770aa1e025d62ddbcd79bda7453fdd98ece4030ba03599f16588fcf483657e"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.0+2/OpenFHE.v1.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
