[[OpenFHE]]
arch = "aarch64"
git-tree-sha1 = "e74cb1462ee0feca99602a8d992ba2ffd12195e7"
julia_version = "1.10.0"
os = "macos"

    [[OpenFHE.download]]
    sha256 = "36f60ff018e1ea4e615ed13639d72f16962d39858d30c992cf5679292b9cf3a9"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[OpenFHE]]
arch = "aarch64"
git-tree-sha1 = "e74cb1462ee0feca99602a8d992ba2ffd12195e7"
julia_version = "1.11.1"
os = "macos"

    [[OpenFHE.download]]
    sha256 = "36f60ff018e1ea4e615ed13639d72f16962d39858d30c992cf5679292b9cf3a9"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[OpenFHE]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cd261d2c3522196cce86f312bf7c8617ec19dfe"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "89808bf2eca73f32cdc0c3f604b66bbfe3d4d5e827c1923cb9f7bc212a0d4dd0"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[OpenFHE]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cd261d2c3522196cce86f312bf7c8617ec19dfe"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "89808bf2eca73f32cdc0c3f604b66bbfe3d4d5e827c1923cb9f7bc212a0d4dd0"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.aarch64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[OpenFHE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a300902d8153895b571a82601564ffad8dfaeda2"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "f942140f6fa3b1da817a6f3b31011bfc511729db201f25f26daaeeee62aa3b91"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[OpenFHE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a300902d8153895b571a82601564ffad8dfaeda2"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "f942140f6fa3b1da817a6f3b31011bfc511729db201f25f26daaeeee62aa3b91"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[OpenFHE]]
arch = "x86_64"
git-tree-sha1 = "3953138281a9967e2c11d8b288cc1412a7d0342d"
julia_version = "1.10.0"
os = "macos"

    [[OpenFHE.download]]
    sha256 = "7588affcf08cd447308ac3792b3f3791518d241e75016769b79f3bf57379e868"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[OpenFHE]]
arch = "x86_64"
git-tree-sha1 = "3953138281a9967e2c11d8b288cc1412a7d0342d"
julia_version = "1.11.1"
os = "macos"

    [[OpenFHE.download]]
    sha256 = "7588affcf08cd447308ac3792b3f3791518d241e75016769b79f3bf57379e868"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77fcbbd6f7c7b47246172bb0447e93a0f637f04a"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "6d3dfde6465a0610c543d5e984aa3fb4c7fca00376028cb2a91d6e7d34e16cb9"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77fcbbd6f7c7b47246172bb0447e93a0f637f04a"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "6d3dfde6465a0610c543d5e984aa3fb4c7fca00376028cb2a91d6e7d34e16cb9"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "495ad2aee9cbf588f893d06ffeb3fbac27aac495"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "0ff0c9a0162626db3b6bdb2b50b5ad7f5bb2d723fd10cd63add62eb69907a3f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "495ad2aee9cbf588f893d06ffeb3fbac27aac495"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "0ff0c9a0162626db3b6bdb2b50b5ad7f5bb2d723fd10cd63add62eb69907a3f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[OpenFHE]]
arch = "x86_64"
git-tree-sha1 = "e243c00d738bc3fa5c9a94f044ad424b9b5e8689"
julia_version = "1.10.0"
os = "freebsd"

    [[OpenFHE.download]]
    sha256 = "f7b86735dd9abe449717e5a7c99eb82f7f46437c09fcb4cd8cedde5e010bb770"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[OpenFHE]]
arch = "x86_64"
git-tree-sha1 = "e243c00d738bc3fa5c9a94f044ad424b9b5e8689"
julia_version = "1.11.1"
os = "freebsd"

    [[OpenFHE.download]]
    sha256 = "f7b86735dd9abe449717e5a7c99eb82f7f46437c09fcb4cd8cedde5e010bb770"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-unknown-freebsd-julia_version+1.11.1.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cb821522ca9f7d271abfb7f19fc124f83533135"
julia_version = "1.10.0"
os = "windows"

    [[OpenFHE.download]]
    sha256 = "6df8fa2f17b9457f6f950eebfad7d41dbf420409ce7ccfdc315a1ad9e18db89f"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cb821522ca9f7d271abfb7f19fc124f83533135"
julia_version = "1.11.1"
os = "windows"

    [[OpenFHE.download]]
    sha256 = "6df8fa2f17b9457f6f950eebfad7d41dbf420409ce7ccfdc315a1ad9e18db89f"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-w64-mingw32-cxx03-julia_version+1.11.1.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5a4329cec740dde12948740c5d194ce5f086ba9"
julia_version = "1.10.0"
os = "windows"

    [[OpenFHE.download]]
    sha256 = "6d55a65c7fe0cf0723aaaba4b60c712e2c7d81c426af181e2fc61baa22a1c68d"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5a4329cec740dde12948740c5d194ce5f086ba9"
julia_version = "1.11.1"
os = "windows"

    [[OpenFHE.download]]
    sha256 = "6d55a65c7fe0cf0723aaaba4b60c712e2c7d81c426af181e2fc61baa22a1c68d"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.2.4+0/OpenFHE.v1.2.4.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
