[[OpenFHE]]
arch = "aarch64"
git-tree-sha1 = "7bd0e3c685fc1136b93c0394d1bcae97ae2017ac"
os = "macos"

    [[OpenFHE.download]]
    sha256 = "cf272798e38f3e78b8d3bbc1b9e92488f5686b527cecf2c69e4bfba14839872f"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.2+0/OpenFHE.v1.4.2.aarch64-apple-darwin.tar.gz"
[[OpenFHE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cbf9b35b2925f1fac073dc8fe9f2a0bb0f6c365"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "7b491efb7bb9b34260c5f19deaaf25b7abf46ebc2fb09a0cda189928f3e2641f"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.2+0/OpenFHE.v1.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenFHE]]
arch = "aarch64"
git-tree-sha1 = "29954d9f2c21f1a54a913b544ab85c5a2a841ba0"
os = "freebsd"

    [[OpenFHE.download]]
    sha256 = "0951dea7c002c9d9209e21b7c477ac387bb6d21c4a4e37f059f1aa0c19235c31"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.2+0/OpenFHE.v1.4.2.aarch64-unknown-freebsd.tar.gz"
[[OpenFHE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bb921f1de9f645b2957eec6eb43901d98394a4d"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "928d7f0a569846683d3165f084f5fee0753a902a3bb27189cb15ead1b95d50c8"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.2+0/OpenFHE.v1.4.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[OpenFHE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2059dbd8a012a606a03caa21f74e6b25eec5244"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "a56f840086b54754ad41df26706615ea65905615fd9970213e01c530373c2924"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.2+0/OpenFHE.v1.4.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenFHE]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72ac21e1b8bd711aa9d010b6cd791e42b080f0eb"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "25e1d4d19772887311492f88121af9da548fa9bf55f24643197052d8e821e7dc"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.2+0/OpenFHE.v1.4.2.riscv64-linux-gnu-cxx11.tar.gz"
[[OpenFHE]]
arch = "x86_64"
git-tree-sha1 = "891f95feef033658deaea527e0665e16ca4ab6b9"
os = "macos"

    [[OpenFHE.download]]
    sha256 = "bf40a0e9429290b785e7779b6486e35ed7c27c50a31ce67362ec5823746d6110"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.2+0/OpenFHE.v1.4.2.x86_64-apple-darwin.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fffbb7803d9b0fc3514331ac84b0e6e913b80852"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "111aef0c9e67af6c26726c0f4549379466547007a76c7153c0524e0a427c24e5"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.2+0/OpenFHE.v1.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenFHE]]
arch = "x86_64"
git-tree-sha1 = "446dbf5629c7a4c977e9d97d8470836eeed09fb1"
os = "freebsd"

    [[OpenFHE.download]]
    sha256 = "8e93ad2c93db25078fcbcd05eabb355c629edc8f938f53df0f73c92aaac99551"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.2+0/OpenFHE.v1.4.2.x86_64-unknown-freebsd.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7dc917eec920895c3bc011b4001f21adb50cdd36"
os = "windows"

    [[OpenFHE.download]]
    sha256 = "14242a6388de54171f304b7d494205bef342956c3a6fda2a7d1b241ae902f0f7"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.4.2+0/OpenFHE.v1.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
